# Generated by Django 5.2.5 on 2025-09-19 00:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='business/favicons/', verbose_name='favicon.ico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('description', models.TextField(blank=True, verbose_name='Общее описание бизнеса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Активированный бизнес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, default='Вся Беларусь', max_length=255, null=True, verbose_name='Локация')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, help_text='Пространство имён для slug (опционально)', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('unit', models.CharField(choices=[('pcs', 'Штука'), ('kg', 'Килограмм'), ('ltr', 'Литр'), ('m', 'Метр'), ('pack', 'Упаковка')], default='pcs', max_length=10, verbose_name='Единица товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу товара')),
                ('currency', models.CharField(blank=True, choices=[('BYN', 'Белорусский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль')], max_length=10, null=True, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли товар для продажи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('rating', models.FloatField(default=0, help_text='Средний рейтинг товара')),
                ('delivery_info', models.CharField(blank=True, default='Самовывоз', help_text='Информация по доставке', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['business', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, help_text='Пространство имён для slug (опционально)', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('template', models.CharField(choices=[('default', 'Стандарт'), ('modern', 'Современный')], default='default', max_length=50)),
                ('content', models.TextField(blank=True, verbose_name='Контент лендинга (HTML/JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Лендинг',
                'verbose_name_plural': 'Лендинги',
            },
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messenger_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'ВКонтакте'), ('skype', 'Skype')], max_length=20, verbose_name='Тип мессенджера')),
                ('identifier', models.CharField(max_length=255, verbose_name='Идентификатор или ссылка')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('benefits', 'Выгоды'), ('products', 'Продукты'), ('testimonials', 'Отзывы'), ('faq', 'FAQ'), ('cta', 'CTA'), ('about', 'О компании'), ('contacts', 'Контакты'), ('custom', 'Кастомный')], default='custom', max_length=50, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент (HTML)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='landing/sections/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение секции',
                'verbose_name_plural': 'Изображения секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, help_text='Пространство имён для slug (опционально)', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('unit', models.CharField(choices=[('acad_hour', 'Академический час'), ('session', 'Сеанс'), ('haircut', 'Стрижка'), ('consultation', 'Консультация'), ('visit', 'Визит'), ('package', 'Пакет'), ('service', 'Услуга'), ('hour', 'Час'), ('day', 'День'), ('task', 'Задача')], default='service', max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, choices=[('BYN', 'Белорусский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль')], help_text='Валюта', max_length=10, null=True)),
                ('place_of_service', models.CharField(blank=True, help_text='Например, на дому, в салоне и т.п.', max_length=255, verbose_name='Место оказания услуги')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность услуги (минуты)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['business', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность / специализация')),
                ('bio', models.TextField(blank=True, verbose_name='Описание / биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.FloatField(default=0.0, help_text='Средний рейтинг мастера от 0 до 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Мастер / специалист',
                'verbose_name_plural': 'Мастера / специалисты',
            },
        ),
    ]
