# Generated by Django 5.2.5 on 2025-08-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_usersociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialLink',
        ),
    ]
