# Generated by Django 5.2.5 on 2025-08-27 07:02

import apps.users.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, verbose_name='Аватар'),
        ),
    ]
