# Generated by Django 5.2.5 on 2025-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_digits',
            field=models.CharField(blank=True, help_text="Автоматически генерируется из поля 'Телефон (как ввёл пользователь)'", max_length=50, verbose_name='Телефон (только цифры)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_display',
            field=models.CharField(blank=True, help_text='Формат на усмотрение пользователя: +375(25)963-3344 или 103', max_length=50, verbose_name='Телефон (как ввёл пользователь)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
