# Generated by Django 5.2.5 on 2025-08-29 06:38

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text="Имя URL-шаблона с namespace (например: 'landing:policy_detail')", max_length=200)),
                ('url_params', models.JSONField(blank=True, help_text="Параметры для reverse(), например: {'slug': 'privacy-policy'}", null=True)),
                ('external_url', models.URLField(blank=True, help_text='Внешняя ссылка (например: https://t.me/moloshop)', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active_link', models.BooleanField(default=True, help_text='Активная ссылка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.profilemenucategory')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню личного кабинета',
            },
        ),
    ]
