# Generated by Django 5.2.5 on 2025-08-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilemenucategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='profilemenucategory',
            name='url_params',
            field=models.JSONField(blank=True, help_text='Параметры для reverse(), например: {"slug":"politika-konfidentsialnosti"}', null=True),
        ),
    ]
