# Generated by Django 5.2.5 on 2025-08-30 19:49

import apps.users.utils.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.utils.avatar.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
