# Generated by Django 5.2.5 on 2025-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number_display',
            field=models.CharField(blank=True, help_text='Формат на усмотрение пользователя: +375(25)963-3344 или 103', max_length=50, verbose_name='Телефон'),
        ),
    ]
