# Generated by Django 5.2.5 on 2025-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_phone_number_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания кода'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Гость'), (1, 'Пользователь'), (2, 'Руководитель'), (3, 'Начальник'), (4, 'Мастер'), (5, 'Сотрудник')], default=0, verbose_name='Статус пользователя'),
        ),
    ]
