# Generated by Django 5.2.5 on 2025-09-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Гость'), (1, 'Пользователь'), (2, 'Сотрудник'), (3, 'Мастер'), (4, 'Руководитель'), (5, 'Администратор'), (6, 'Суперпользователь')], default=0, verbose_name='Статус пользователя'),
        ),
    ]
