# Generated by Django 5.2.5 on 2025-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoreplacement',
            options={'verbose_name': 'SEO-Замена', 'verbose_name_plural': 'SEO-Замены'},
        ),
        migrations.AlterModelOptions(
            name='stopword',
            options={'verbose_name': 'SEO-Стоп-слово', 'verbose_name_plural': 'SEO-Стоп-слова'},
        ),
        migrations.AddField(
            model_name='footermenucategory',
            name='external_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка (например: https://t.me/moloshop)', null=True),
        ),
        migrations.AlterField(
            model_name='footermenucategory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
