# Generated by Django 5.2.5 on 2025-08-23 09:44

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seoreplacement_options_alter_stopword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsInstructions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, help_text='Пространство имён для slug (опционально)', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Политика, правила, инструкции',
                'verbose_name_plural': 'Политика, правила, инструкции',
            },
        ),
    ]
