# Generated by Django 5.2.5 on 2025-08-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contractsinstructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsinstructions',
            options={'verbose_name': 'Политику, правила, инструкции', 'verbose_name_plural': 'Политики, правила, инструкции'},
        ),
    ]
